### ISSUE TITLE
Add pr-size-labeler for Github Action

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#12]
> [!IMPORTANT]
> Read issue #2 first

I've seen how this Github Action works and would like to add it to my repository. If anyone wants to try to add it, go ahead.

This is the repository with the documentation: https://github.com/CodelyTV/pr-size-labeler

Thank you very much.

**Comment by ivonasto** [comment]
Hey, I would like to do this one :)

**Comment by nmarulo** [comment]
@ivonasto It's all yours 👍

**Comment by ivonasto** [comment]
Thanks! Do you want to keep the default settings for PR size: xs - 10 lines, s - 100 lines etc?

**Comment by nmarulo** [comment]
Yes, it looks good.

**Comment by ivonasto** [comment]
We tested it with @KarakoA and saw that PRs from forks do not get labelled.

Fixed it in #30 - it turns out `pull_request_target` is mandatory (and confined only to the specified permissions in the labeller.yml file)

**Comment by nmarulo** [comment]
@ivonasto @KarakaA

Yes, I saw it. I was going to check it out later.

Thank you very much.
