### ISSUE TITLE
Improve Folder Structure for Better Code Organization

### ISSUE THREAD

**Issue by PavanendraBaahubali** [despensa-app/despensa-rest-api#14]
I reviewed your code and noticed that the project structure could be improved for better organization and easier navigation. Specifically, in the path:

## `src/main/java/dev/nmarulo/depensaapp/app/products`

Currently, all services, controllers, and repositories are placed within the same `products` folder. This structure makes it more difficult to navigate through the project and maintain separation of concerns.

## Suggestion:

To improve the organization, you could create subfolders within the `products` folder, such as:

- `productServices`
- `productController`
- `productRepositories`

This structure would follow better practices and make the codebase easier to manage and navigate in the long run.

**Comment by PavanendraBaahubali** [comment]
So, can I work on this?

**Comment by nmarulo** [comment]
Hello @PavanendraBaahubali. Thank you for your interest.

It is not very clear to me the final result, if you prefer to do the PR or detail me a little more about the change.

However, if you mean partly why the APP package?
My idea was to locate in one place all the resources (API) grouping them by “functionalities”, for example, the resources related only to the products are in the app/products package and so on with the others.
I'm not following any architecture, I just found it comfortable this way. I am not saying that it is the best and if the need to change it arises, it will be changed. Moreover, I hope it will be so, I am not closed to change 🙂 🙂

**Comment by PavanendraBaahubali** [comment]
Thank you for the clarification!

To enhance the organization while keeping your current structure, one suggestion is to create subfolders within the products folder. 

- This would help follow best practices, keeping services, controllers, and repositories separated, which makes the codebase easier to manage and navigate in the long run.

- Of course, this is just a suggestion to improve maintainability. I understand the need for flexibility and that you’ve structured it for convenience, so feel free to take it into consideration whenever you feel it's necessary.

Thank You.

> Hello @PavanendraBaahubali. Thank you for your interest.
> 
> It is not very clear to me the final result, if you prefer to do the PR or detail me a little more about the change.
> 
> However, if you mean partly why the APP package? My idea was to locate in one place all the resources (API) grouping them by “functionalities”, for example, the resources related only to the products are in the app/products package and so on with the others. I'm not following any architecture, I just found it comfortable this way. I am not saying that it is the best and if the need to change it arises, it will be changed. Moreover, I hope it will be so, I am not closed to change 🙂

**Comment by nmarulo** [comment]
@PavanendraBaahubali I agree with your comments.

Although, I still don't see the final result, if it's ok you can make a PR, if it's not too expensive with the minimum changes, and so we can see some code.
