### ISSUE TITLE
Add sample shopping lists

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#18]
> [!IMPORTANT]
> Read issue #2 first

Modify the [data.sql](https://github.com/despensa-app/despensa-rest-api/blob/91e2b5db6043fdd1a14535632683dac089809461/src/main/resources/db/data.sql) file and add the following at the end:

```sql
INSERT INTO shopping_list (id, name, total_products, total_calories, total_price, user_id, created_at, updated_at)
VALUES (1, 'Lista de ejemplo', 6, 0.00, 10.09, 1, '2024-10-01 21:16:55', '2024-10-01 21:16:55'),
       (2, 'Lista 02', 0, 0.00, 0.00, 1, '2024-10-01 21:17:24', '2024-10-01 21:17:24');

INSERT INTO products_has_shopping_list (product_id, shopping_list_id, unit_type_id, units_per_product, total_calories,
                                        total_price, selected)
VALUES (4567, 1, 1, 1, 0.00, 1.45, 0),
       (4569, 1, 1, 1, 0.00, 2.65, 0),
       (4576, 1, 1, 1, 0.00, 1.25, 0),
       (4597, 1, 1, 1, 0.00, 1.05, 0),
       (4616, 1, 1, 1, 0.00, 1.00, 0),
       (4637, 1, 1, 1, 0.00, 2.69, 0);
```

> [!NOTE]
> Remember to add a semicolon (`;`) on [line 526](https://github.com/despensa-app/despensa-rest-api/blob/91e2b5db6043fdd1a14535632683dac089809461/src/main/resources/db/data.sql#L526).

**Comment by smzoha** [comment]
Hi. I'd like to try my hand at this. This would be my first ever contribution to a repo in Github and I'd like to start small and easy. :)

**Comment by harshitadharamansharma** [comment]
Can you assign this to me?

**Comment by nmarulo** [comment]
@smzoha It's all yours 👍

**Comment by smzoha** [comment]
@nmarulo Thank you! I'll get the PR up soon.
