### ISSUE TITLE
📣 Hacktoberfest 2024

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#2]
> [!IMPORTANT]
> - The issues that I create for the hacktoberfest will be closed until the 1st of October.
> - The issues noted with the `hacktoberfest` label, are for event and will be enabled on October 1st. **They cannot be resolved before that date.**
> - Please do not create Pull Requests from issues noted with the `hacktoberfest` label that are not assigned to you.
> - When you are assigned an issue, **you must confirm it by commenting on the issue within 24 hours after the assignment**, this is just so I can know if you have heard or not, if I do not receive a reply I will assign it to someone else.

Hello everyone 👋, I'm Nicolás, Java programmer and I'm working on this project as a hobby. I've been learning and practicing Spring-boot and Angular, and I'm applying little by little, everything I've learned, in this project.

It doesn't matter if you are just starting or have been working with these two technologies for a short time, I will try to help those who want to make their first contributions on github, creating some simple issues.

Find all the issues for the hacktoberfest [here](https://github.com/despensa-app/despensa-rest-api/milestone/1).

Each issue noted with `hacktoberfest` must be completed within a week and **you can only do one per week**, this is to give more participants a chance. If you are interested in resolving any issues or have questions, please comment in the corresponding issue.

Each issue will also have a label indicating its level of difficulty:

- `Easy`: I practically give you the solution in the issue, you only have to follow the indications. These issues are focused to developers who want to make their first contributions, so if several people ask for the same issue I will decide who to assign it to regardless of the order of arrival.
- `Medium`: I explain you what to do and I may give part of the solution.
- `Complex`: I explain you what to do, but it will have a part of research on your own.

You can also suggest issues. These do not have a maximum time to be completed and you can create as many as you see fit.

Thank you very much 😁.

> [!NOTE]
>Please let me know if you can't complete the issue. These things happen, no problem 👍.

**Comment by scamitt** [comment]
Hi Nicolás, when will you be able to assign the issues to me, or when can I start working on them?

**Comment by nmarulo** [comment]
Hi @scamitt. From the first of October I will open all the incidents.

**Comment by Sofiyan-coder** [comment]
Hi @nmarulo I would like work on #3 , #8 , #7 , #6  issues I request you to assign me these issues, So I can start contributing to the Open source community your support will mean a lot to me!

Thank you  !

**Comment by nmarulo** [comment]
> Hi @nmarulo,
> 
> I'm excited to see Spring Boot projects participating in Hacktoberfest, and I'd love to contribute! You can go ahead and assign me any of the issues #3, #5, or #6 for now.
> 
> Additionally, I would appreciate it if you could open some intermediate-level issues that require more in-depth knowledge of Spring Boot or Java, as I would love to take on those challenges as well!
> 
> Looking forward to contributing!

Hi @RehanChalana. Thanks for your interest.

For the moment I have focused on tasks that people can do even without running the project just for the purpose of helping those who want to make their first contributions.

I currently have a fairly large task list for this project and I'm trying to break it down into small, easy to tackle tasks. I will add more, soon.

**Comment by nmarulo** [comment]
@RehanChalana Since you asked me, you might be interested in issue #22, comment on the issue if you are interested 👍.

**Comment by nmarulo** [comment]
Due to personal issues I have not been able to create more issues, but I have been organizing my notes, from which I will try to get more issues (there are quite a lot) so more people can participate.

**Comment by nmarulo** [comment]
Many thanks to all who participated.

There are only a few days left until the end of October, so, maybe I will not create more issues, concrete, for the hacktoberfest (although there are still many issues to be written).

I will continue working on the project, but it is still open to suggestions, comments and issues.

Thanks again 😄
