### ISSUE TITLE
Custom JWT error message

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#22]
> [!IMPORTANT]
> Read issue #2 first

I want that when the token fails, it returns a customizable error message, similar to the `ControllerExceptionHandler` class where I return an `ErrorRes` object.

Maybe this documentation gives a clue as to what needs to be done: https://docs.spring.io/spring-security/reference/servlet/oauth2/resource-server/bearer-tokens.html

To make the token fail for time, just modify the `app.jwt.expires-at` property of the `application.properties` file.

This issue is open to changes or suggestions.

**Comment by ArinNigam** [comment]
I would like to work on this issue

**Comment by Madhan-ms-21** [comment]
Hi @nmarulo 

I would like to contribute for the same, this is my first contribution , i hope with proper instruction i can help you resolve this

**Comment by nmarulo** [comment]
@Madhan-ms-21 It's all yours 👍

**Comment by Madhan-ms-21** [comment]
@nmarulo 

Here are few Clarifications needed from your side

1) Token Fails
   In what cases you want to return a customizable message , 
   I can think of One at Invalid tokena case and other at  Expired Token case .
   
   Let me Know anything else you are looking for?

**Comment by nmarulo** [comment]
@Madhan-ms-21 That's right. Only those two cases.

**Comment by Madhan-ms-21** [comment]
@nmarulo 
It seems we dont have Authorization constraint for api access as of now when i tested in postman .

All Endpoints which are accessible without bearer token , just to confirm ?

**Comment by nmarulo** [comment]
@Madhan-ms-21 
Correct. Currently, everything can be accessed without authentication.

**Comment by Srijan25** [comment]
can you assign it to me i have exp in jwt

**Comment by nmarulo** [comment]
He still has a few days to complete the issue.

**Comment by Ankush-Paul-02** [comment]
Can you please assign me, I would like to fix this issue.

**Comment by nmarulo** [comment]
As stated in issue #1

> Each issue noted with hacktoberfest must be completed within a week and you can only do one per week, this is to give more participants a chance. ...

It's okay that you were not able to complete it, I appreciate your effort and interest.

**Comment by Ankush-Paul-02** [comment]
@nmarulo can you please assign me this

**Comment by nmarulo** [comment]
@Srijan25 Do you still want to do this issue?

**Comment by nmarulo** [comment]
@Ankush-Paul-02 Do you still want to do this issue?

**Comment by Ankush-Paul-02** [comment]
Yes I want to do this

**Comment by nmarulo** [comment]
@Ankush-Paul-02 It's all yours 👍

**Comment by nmarulo** [comment]
As stated in issue #2

> Each issue noted with hacktoberfest must be completed within a week and you can only do one per week, this is to give more participants a chance. ...

It's okay that you were not able to complete it, I appreciate your effort and interest.

**Comment by JinnJarBurger** [comment]
@nmarulo could you assign me this issue? Thanks!

**Comment by nmarulo** [comment]
@JinnJarBurger It's all yours 👍

**Comment by JinnJarBurger** [comment]
> @JinnJarBurger It's all yours 👍

alright on it!
