### ISSUE TITLE
Audit annotations for the "ShoppingList" entity

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#23]
> [!IMPORTANT]
> Read issue #2 first

Implement the use of `@CreatedDate` and `@LastModifiedDate` annotations in the [`ShoppingList`](https://github.com/despensa-app/despensa-rest-api/blob/450c0ec47c199c81d87a56f8f336bb6b605e6c18/src/main/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingList.java) entity, in the `createdAt` and `updatedAt` fields respectively.

Remove the lines of code where these dates are set manually.

Doc: https://docs.spring.io/spring-data/rest/reference/data-commons/auditing.html

**Comment by JinnJarBurger** [comment]
Hello @nmarulo, could you please assign this issue to me?

**Comment by JinnJarBurger** [comment]
Alright, on it then!

**Comment by JinnJarBurger** [comment]
> @JinnJarBurger It's all yours 👍

on it!

**Comment by JinnJarBurger** [comment]
Hello @nmarulo, I've sent you an access request to fork the `API`s on `Postman`. Could you please grant me access my email is -> `adnanhossain274@gmail.com`. Thanks!

**Comment by nmarulo** [comment]
@JinnJarBurger I'm checking the postman config, but this should be public.

**Comment by nmarulo** [comment]
@JinnJarBurger I have corrected the postman, thanks for letting me know.
