### ISSUE TITLE
Update "application-boxfuse.properties" file 

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#3]
> [!IMPORTANT]
> Read issue #2 first

Replace the contents of the `application-boxfuse.properties` file with:

```properties
spring.config.import=application-production.properties
# Spring auto-configuration properties
spring.profiles.default=boxfuse
```

**Comment by Sofiyan-coder** [comment]
Hello @nmarulo,

I have thoroughly studied the project and developed the necessary skills to contribute with high-quality pull requests. Assigning me this issue would greatly benefit my career in open source, and I am eager to assist in any way I can. and want to work on this project now and in future!

**Comment by Sofiyan-coder** [comment]
Hi @nmarulo I would like to work on this issue assign me this!

**Comment by nmarulo** [comment]
@Sofiyan-coder The incidences that I create are only one per week for the same person, this is to give opportunities to more people. This is mentioned in issue #2.

**Comment by ArturWood** [comment]
Hello @nmarulo, can you assign this issue to me, please? This is my first time with Open source. Hope I get to help

**Comment by nmarulo** [comment]
@ArturWood It's all yours 👍

**Comment by ArturWood** [comment]
Thanks for the opportunity @nmarulo 

I've just created the PR: https://github.com/despensa-app/despensa-rest-api/pull/25

Please check if everything is ok
