### ISSUE TITLE
Create "randomImage" method

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#34]
> [!IMPORTANT]
> Read issue #2 first

Create the `randomImage` method in the class [FakeTestUtil](https://github.com/despensa-app/despensa-rest-api/blob/b03897dcd0cc8ba04d11e46e561a9c041ed0a014/src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java) and you must use [“image()” from the datafake](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/Internet.html) to generate a url.

And use it to replace the text on the line https://github.com/despensa-app/despensa-rest-api/blob/b03897dcd0cc8ba04d11e46e561a9c041ed0a014/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L72

**Comment by JavierABarreto** [comment]
Hello @nmarulo, I would like to contribute!

**Comment by nmarulo** [comment]
@JavierABarreto It's all yours 👍

**Comment by JavierABarreto** [comment]
Thanks!
