### ISSUE TITLE
Create "randomBigDecimal" method

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#35]
> [!IMPORTANT]
> Read issue #2 first

Create the `randomBigDecimal` method in the class [FakeTestUtil](https://github.com/despensa-app/despensa-rest-api/blob/b03897dcd0cc8ba04d11e46e561a9c041ed0a014/src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java). The library used is that of [datafaker](https://www.datafaker.net/documentation/providers/).

This method must return a BigDecimal object, the value must be positive, between 1 and 1000 and have decimals.

And use it to replace:

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L72

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L74

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java#L51-L52

**Comment by ReBy298** [comment]
Hi! I would like to try this issue  :D

**Comment by KaroK365** [comment]
Hi would like to contribute to this issue 😊

**Comment by nmarulo** [comment]
@KaroK365 It's all yours 👍

**Comment by manuaishika** [comment]
id like to work on this issue

**Comment by nmarulo** [comment]
@manuaishika This issue is already assigned, I will try to create some more.
