### ISSUE TITLE
Create "randomFuture" method

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#36]
> [!IMPORTANT]
> Read issue #2 first

Create the `randomFuture` method in the class [FakeTestUtil](https://github.com/despensa-app/despensa-rest-api/blob/b03897dcd0cc8ba04d11e46e561a9c041ed0a014/src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java). The library used is that of [datafaker](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/TimeAndDate.html).

Generates a future time from now.

And use it to replace:

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L77

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L91

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java#L39

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java#L54

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/unitytypes/UnitTypeServiceTestUtil.java#L50

**Comment by ArturWood** [comment]
Hello @nmarulo ! I would like to try solve this one

**Comment by nmarulo** [comment]
@ArturWood It's all yours 👍

**Comment by ArturWood** [comment]
Thanks!
