### ISSUE TITLE
Create "randomPast" method

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#37]
> [!IMPORTANT]
> Read issue #2 first

Create the `randomPast` method in the class [FakeTestUtil](https://github.com/despensa-app/despensa-rest-api/blob/b03897dcd0cc8ba04d11e46e561a9c041ed0a014/src/test/java/dev/nmarulo/depensaapp/FakeTestUtil.java). The library used is that of [datafaker](https://javadoc.io/doc/net.datafaker/datafaker/latest/net/datafaker/providers/base/TimeAndDate.html).

Generates a past time from now.

And use it to replace:

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L76

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/products/ProductServiceTestUtil.java#L90

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java#L38

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/shoppinglist/ShoppingListServiceTestUtil.java#L53

https://github.com/despensa-app/despensa-rest-api/blob/5ec3f86672238b5eafbe2b3876b632144befcecd/src/test/java/dev/nmarulo/depensaapp/app/unitytypes/UnitTypeServiceTestUtil.java#L49

**Comment by sathwikmatsa** [comment]
I'd like to work on this.

**Comment by ReBy298** [comment]
Hi, I would like to work in this issue :)

**Comment by nmarulo** [comment]
@ReBy298 It's all yours 👍

**Comment by ReBy298** [comment]
> @ReBy298 It's all yours 👍
Thank you so much, I would start to work on it <3
