### ISSUE TITLE
Create dockerdev profile

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#5]
> [!IMPORTANT]
> Read issue #2 first

Create the `application-dockerdev.properties` file in the `src/main/resources/` path with the following content:

```properties
spring.config.import=application.properties
# Spring auto-configuration properties
spring.sql.init.mode=always
```

Modify the file `docker compose.run.xml`, [on line 5](https://github.com/despensa-app/despensa-rest-api/blob/a13fd930a8e2343ff1043355f010f9dc3501dd4b/.run/docker%20compose.run.xml#L4-L5), after the `settings` element, add the following line:

```xml
<option name="composeProjectName" value="dockerdev" />
```

Modify the file `Dockerfile`, [on line 43](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/Dockerfile#L43), change the argument:

`-Dspring.profiles.active=local`

by

`-Dspring.profiles.active=dockerdev`

Finally check that when running the `compose.yaml` the application is launched using the new profile.

**Comment by Sofiyan-coder** [comment]
Hello@nmarulo,

I have thoroughly studied the project and developed the necessary skills to contribute with high-quality pull requests. Assigning me this issue would greatly benefit my career in open source, and I am eager to assist in any way I can. and want to work on this project now and in the future!

**Comment by 7vk** [comment]
Hey @nmarulo ! I’m new to contributing on GitHub and would love to get started with something straightforward to ease my way in. This would be my first ever contribution, so I’m hoping to get a shot. :)

**Comment by nmarulo** [comment]
@7vk It's all yours 👍
