### ISSUE TITLE
Translate the README.md file into English

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#6]
> [!IMPORTANT]
> Read issue #2 first

1. Create a folder named `translations`.
2. Create a file named `README.en.md`.
3. Update the `README.md` file, adding before the `Descripción` header the following:

```
📚 **Translations Readme**: [English](translations/README.en.md)
```

**Comment by mariasoria** [comment]
Hi! Could you assign this Issue to me? I'd like to do it 🙏🏼
Thank you!

**Comment by Sofiyan-coder** [comment]
Hello@nmarulo,

I would like to work on this issue, to start my open source career, I request you to assign me!

**Comment by nmarulo** [comment]
I have to upload some changes, so I will postpone the assignment for a few days.

**Comment by mariasoria** [comment]
That's fine, Nicolás. Thank you very much for letting us now 🙌🏼.

**Comment by mohitahlawat2001** [comment]
i want to work on this issue

**Comment by UnpolishedNoob** [comment]
Hello @nmarulo, would you like to assign me this issue? I've already worked on it, need permission to make a PR

**Comment by manuaishika** [comment]
hi @nmarulo could you please assign this issue to me,i might have valuable additions to make.

**Comment by nmarulo** [comment]
As I do not consider it very important, I have not taken the time to upload what I need to the readme. I will try to do it today or during the weekend. After that I will assign this issue to someone.

**Comment by nmarulo** [comment]
@mariasoria Do you still want to make this issue?

**Comment by mariasoria** [comment]
Hi @nmarulo ! Yes, please 🙏🏾 

Thank you very much

**Comment by mariasoria** [comment]
Hi @nmarulo I've seen that you have got a link in the README.md to one of the discussions in this repository. I can see that it is also in Spanish. Do you want me to create another discussion in English and link it to the README.en.md?
Thank you

**Comment by nmarulo** [comment]
> Hi @nmarulo I've seen that you have got a link in the README.md to one of the [discussions](https://github.com/despensa-app/despensa-rest-api/discussions/29) in this repository. I can see that it is also in Spanish (even though you can translate it in there). Do you want me to create another discussion in English and link it to the README.en.md?

I don't see it necessary, since github facilitates the automatic translation.

![image](https://github.com/user-attachments/assets/657d69e2-2a76-4bb9-b6bc-bfeba444dd5d)

> 
> The `CONTRIBUTING.md` is also in Spanish. Do you want me to translate that as well? Thank you

Later, possibly, I will create an issue, but not for now.

Thank you
