### ISSUE TITLE
Update type in Product database

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#7]
> [!IMPORTANT]
> Read issue #2 first

Change the type from `Integer` to `Long` on [line 28](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/java/dev/nmarulo/depensaapp/app/products/Product.java#L28) of the `Product` class.

This change will cause the application to no longer compile with maven, because you have to update all classes related to the `Product` entity ID field.

<details>
<summary>List of classes to be modified</summary>

![image](https://github.com/user-attachments/assets/10ddd4ea-ca97-4ff8-aea9-1ee41de55122)

</details>

Finally, in the SQL script `schema.sql` change the type to `BIGINT` on [line 20](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L20) and [line 97](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L97).

> [!NOTE]
> The following script is a note to myself, so you can ignore it.

<details>
<summary>Script a ejecutar en la base de datos de demo</summary>

```sql
ALTER TABLE products_has_shopping_list
    DROP FOREIGN KEY fk_products_has_shopping_list_products;
ALTER TABLE products_has_shopping_list
    MODIFY product_id BIGINT;
ALTER TABLE products
    MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE products_has_shopping_list
    ADD CONSTRAINT `fk_products_has_shopping_list_products`
        FOREIGN KEY (`product_id`)
            REFERENCES `products` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
```

</summary>

**Comment by Sofiyan-coder** [comment]
Hello @nmarulo,

I have thoroughly studied the project and developed the necessary skills to contribute with high-quality pull requests. Assigning me this issue would greatly benefit my career in open source, and I am eager to assist in any way I can. and want to work on this project now and in future!

**Comment by nmarulo** [comment]
@Sofiyan-coder It's all yours 👍

**Comment by Sofiyan-coder** [comment]
@nmarulo Update me if any changes are needed and please give feedback if you like my contribution!

**Comment by nmarulo** [comment]
As stated in issue #2

> Each issue noted with hacktoberfest must be completed within a week and you can only do one per week, this is to give more participants a chance. If you are interested in resolving any issues or have questions, please comment in the corresponding issue.

It's okay that you were not able to complete it, I appreciate your effort and interest.

**Comment by JinnJarBurger** [comment]
@nmarulo if possible could you assign the issue to me? Thanks!
