### ISSUE TITLE
Update type in Users database

### ISSUE THREAD

**Issue by nmarulo** [despensa-app/despensa-rest-api#8]
> [!IMPORTANT]
> Read issue #2 first

Change the type from `Integer` to `Long` on [line 25](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/java/dev/nmarulo/depensaapp/app/users/User.java#L25) of the `Users` class.

As in issue #7, this change will cause the application to no longer compile with maven, because you have to update all classes related to the `Users` entity ID field.

<details>
<summary>List of classes to be modified</summary>

![image](https://github.com/user-attachments/assets/32e68fc3-fa0d-44cd-b871-f86cbbeec89e)

</details>

Finally, in the SQL script `schema.sql` change the type to `BIGINT` on [line 39](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L39) and [line 62](https://github.com/despensa-app/despensa-rest-api/blob/1805ef7f4331b77bb8a50d48f5290d4684e2f161/src/main/resources/db/schema.sql#L62).

> [!NOTE]
> The following script is a note to myself, so you can ignore it.

<details>
<summary>Script a ejecutar en la base de datos de demo</summary>

```sql
ALTER TABLE shopping_list
    DROP FOREIGN KEY fk_shopping_list_users1;
ALTER TABLE shopping_list
    MODIFY user_id BIGINT;
ALTER TABLE users
    MODIFY id BIGINT AUTO_INCREMENT;
ALTER TABLE shopping_list
    ADD CONSTRAINT `fk_shopping_list_users1`
        FOREIGN KEY (`user_id`)
            REFERENCES `users` (`id`)
            ON DELETE NO ACTION
            ON UPDATE NO ACTION;
```

</summary>

**Comment by Sofiyan-coder** [comment]
Hello @nmarulo,

I have thoroughly studied the project and developed the necessary skills to contribute with high-quality pull requests. Assigning me this issue would greatly benefit my career in open source, and I am eager to assist in any way I can. and want to work on this project now and in future!

**Comment by nmarulo** [comment]
@gitclonegaurang It's all yours 👍
